#!/bin/sh
echo "Setup script for USB network access..."
echo "Setting up the default gateway"
/sbin/route add default gw 192.168.7.1

echo "Updateing the nameserver entry..."
echo "nameserver 8.8.8.8" >> /etc/resolv.conf

echo "Setting time to GMT+1..."
/usr/bin/ntpdate -b -s -u nl.pool.ntp.org
cp /usr/share/zoneinfo/Europe/Paris /etc/localtime
